package resources;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.InputStreamResource;
import org.springframework.util.Assert;

import play.Logger;
import play.Play;
import play.classloading.ApplicationClasses.ApplicationClass;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

/**
 * TODO: Insert description here. (generated by binyu)
 */
public class PlayAnnotationConfigApplicationContext extends AnnotationConfigApplicationContext {

	private PlayClassPathBeanDefinitionScanner myscanner;

	public PlayAnnotationConfigApplicationContext() {
		super();
		this.myscanner = new PlayClassPathBeanDefinitionScanner(this);
	}

	@Override
	public void scan(String... basePackages) {
		Assert.notEmpty(basePackages,
				"At least one base package must be specified");
		int numOfBeans = this.myscanner.scan(basePackages);
		Logger.info("Found %s beans", numOfBeans);
		super.scan(basePackages);
	}

}
