#!/bin/bash -ae

app_name=AgentMaster
rt_name=play-1.2.4

abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
package_dir=$scripts_dir/../..
rt_home=$package_dir/$rt_name
app_home=$package_dir/$app_name

echo -e "\nscripts_dir is $scripts_dir"
echo -e "\npackage_dir is $package_dir"
echo -e "\nruntime_home is $rt_home"
echo -e "\napp_home is $app_home"

# the conf folder; has conf
app_conf_dir="$app_home/conf"

echo -e "\nActivating application..."
# enter the scripts_dir; this is critical for application log
cd $scripts_dir

# copy the .conf files 
echo 'copy the .conf files '

# create user_data dir if not there
if [ -n "$CRONUSAPP_HOME" ] && [ ! -d "$CRONUSAPP_HOME/.appdata/user_data" ]; then
  echo "create user_data directory $CRONUSAPP_HOME/.appdata/user_data"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data
fi

# copy predefined commands if not there
if [ -n "$CRONUSAPP_HOME" ] && [ ! -d "$CRONUSAPP_HOME/.appdata/user_data/commands" ]; then
  echo "create predefined commands"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data/commands
  cp $app_home/user_data/commands/* $CRONUSAPP_HOME/.appdata/user_data/commands/
fi

# copy predefined nodegroups if not there
if [ -n "$CRONUSAPP_HOME" ] && [ ! -d "$CRONUSAPP_HOME/.appdata/user_data/predefined_nodegroups" ]; then
  echo "create predefined nodegroups"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data/predefined_nodegroups
  cp $app_home/user_data/predefined_nodegroups/* $CRONUSAPP_HOME/.appdata/user_data/predefined_nodegroups/
fi

APPDATA_HOME=$CRONUSAPP_HOME/.appdata

# Starting application

echo 'precomiling app...'
$rt_home/play precompile $app_home; sleep 1;

echo 'precomiled app... Activation completed.'

