#!/bin/bash -ae

app_name=AgentMaster
rt_name=play_runtime

abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
package_dir=$scripts_dir/../..
rt_home=$package_dir/$rt_name
app_home=$package_dir/$app_name

echo -e "\nscripts_dir is $scripts_dir"
echo -e "\npackage_dir is $package_dir"
echo -e "\nruntime_home is $rt_home"
echo -e "\napp_home is $app_home"

# the conf folder; has conf
app_conf_dir="$app_home/conf"

echo -e "\nActivating application..."
# enter the scripts_dir; this is critical for application log
cd $scripts_dir

# copy the .conf files 
echo 'copy the .conf files '

# create user_data dir if not there
if [ ! -d "$CRONUSAPP_HOME/.appdata/user_data" ]; then
  echo "create user_data directory $CRONUSAPP_HOME/.appdata/user_data"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data
fi

# copy predefined commands if not there
if [ ! -d "$CRONUSAPP_HOME/.appdata/user_data/commands" ]; then
  echo "create predefined commands"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data/commands
fi
cp -n $app_home/user_data/commands/* $CRONUSAPP_HOME/.appdata/user_data/commands/

# copy oneclick commands if not there
if [ ! -d "$CRONUSAPP_HOME/.appdata/user_data/cmd_oneclick" ]; then
  echo "create oneclick commands"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data/cmd_oneclick
fi
cp -n $app_home/user_data/cmd_oneclick/* $CRONUSAPP_HOME/.appdata/user_data/cmd_oneclick/

# copy sys commands if not there
if [ ! -d "$CRONUSAPP_HOME/.appdata/user_data/cmd_sys" ]; then
  echo "create sys commands"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data/cmd_sys
fi
cp -n $app_home/user_data/cmd_sys/* $CRONUSAPP_HOME/.appdata/user_data/cmd_sys/

# copy predefined nodegroups if not there
if [ ! -d "$CRONUSAPP_HOME/.appdata/user_data/predefined_nodegroups" ]; then
  echo "create predefined nodegroups"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data/predefined_nodegroups
fi
cp -n $app_home/user_data/predefined_nodegroups/* $CRONUSAPP_HOME/.appdata/user_data/predefined_nodegroups/

# copy predefined jobs if not there
if [ ! -d "$CRONUSAPP_HOME/.appdata/user_data/cmd_jobs" ]; then
  echo "create predefined cmd jobs"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data/cmd_jobs
fi
cp -n $app_home/user_data/cmd_jobs/* $CRONUSAPP_HOME/.appdata/user_data/cmd_jobs/

# copy predefined pkg if not there
if [ ! -d "$CRONUSAPP_HOME/.appdata/user_data/cronus_pkgs" ]; then
  echo "create predefined cronus pkgs"
  mkdir -p $CRONUSAPP_HOME/.appdata/user_data/cronus_pkgs
fi
cp -n $app_home/user_data/cronus_pkgs/* $CRONUSAPP_HOME/.appdata/user_data/cronus_pkgs/

# Starting application

echo 'precomiling app...'
$rt_home/play precompile $app_home; sleep 1;

echo 'precomiled app... Activation completed.'

