#!/bin/bash

echo "Checking availability of java runtime"
echo "authztoken=$AUTHZTOKEN"

if which java > /dev/null 2>&1; then
  JAVA_VER=$(java -version 2>&1 | grep 'java version' | egrep -o '[1-2]\.[6-9]' | tr -d '.')
  echo "java_ver=$JAVA_VER"
  [ "$JAVA_VER" -ge 15 ] && echo "ok, java is 1.5 or newer"; exit 0;
fi

if [[ ! -z "$AUTHZTOKEN" ]]; then
  echo "Installing openjdk7 JRE"
  curl_cmd=
  if hash apt-get 2>/dev/null; then
    curl_cmd="'{\"cmd\": \"apt-get -q -y install openjdk-7-jre\", \"sudoUser\": \"root\"}'"
  elif hash yum 2>/dev/null; then
    curl_cmd="{\"cmd\": \"yum -q -y install java-1.7.0-openjdk\", \"sudoUser\": \"root\"}"
  fi
  echo "$curl_cmd"
  curl -k -H "Authorization:Basic $AUTHZTOKEN" -H "content-type:application/json" -X POST -d "$curl_cmd" https://localhost:19000/admin/executeCmd

  for i in {1..10}; do
    if which java > /dev/null 2>&1; then
      JAVA_VER=$(java -version 2>&1 | grep 'java version' | egrep -o '[1-2]\.[6-9]' | tr -d '.')
      echo "java_ver=$JAVA_VER"
      [ "$JAVA_VER" -ge 15 ] && echo "ok, java is 1.5 or newer"; exit 0;
    fi
    sleep 10
  done

fi

