#!/bin/bash -ae

app_name=AgentMaster
rt_name=play_runtime

abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
package_dir=$scripts_dir/../..
rt_home=$package_dir/$rt_name
app_home=$package_dir/$app_name

echo -e "\nscripts_dir is $scripts_dir"
echo -e "\npackage_dir is $package_dir"
echo -e "\nruntime_home is $rt_home"
echo -e "\napp_home is $app_home"

# the conf folder; has conf
app_conf_dir="$app_home/conf"

# Stopping the current play application: safety meature. make the startup idempotent
echo 'stopping app'
$rt_home/play stop $app_home > /dev/null 2>&1

echo 'removing pid'
rm -f "$app_home/server.pid"

echo 'App stopped!'
