#!/bin/bash -ae

app_name=AgentMaster
rt_name=play_runtime

abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
package_dir=$scripts_dir/../..
rt_home="$package_dir/$rt_name"
app_home="$package_dir/$app_name"

echo -e "\nscripts_dir is $scripts_dir"
echo -e "\npackage_dir is $package_dir"
echo -e "\nruntime_home is $rt_home"
echo -e "\napp_home is $app_home"

# the conf folder; has conf
app_conf_dir="$app_home/conf"

# enter app_home; this is critical for application log
cd $app_home

# cleanup pid if needed
rm -f "$app_home/server.pid"

# Starting application 
if [ ! -z "$1" ]; then
    echo "starting app nodaemon"
    $rt_home/play run $app_home -Dprecompiled=true -Dhttps.port=9443
else
    echo 'starting app'
    setsid $rt_home/play start $app_home -Dprecompiled=true -Dhttps.port=9443
fi

echo 'App started!'

